name: Release APK

on:
  push:
    tags:
      - 'v*'

jobs:
  apk:
    name: Release APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - run: bash ./gradlew assembleRelease
      - uses: actions/upload-artifact@v3
        with:
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          name: Task-APP